apiVersion: apps/v1
kind: Deployment
metadata:
  name: nettools-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nettools
  template:
    metadata:
      labels:
        app: nettools
    spec:
      containers:
      - name: nettools
        image: nicolaka/netshoot:latest
        command: ["sleep", "infinity"]
        ports:
        - containerPort: 80

